/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mpes.sorteio.calendário.jornadas.liga.portugal.gui;

import java.util.HashMap;

/**
 *
 * @author vitorsantos
 */
public class GeneticAlgorithmOptionsPanel extends javax.swing.JPanel {

    static final String DEFAULT_POPULATION_NUMBER = "15";

    /**
     * Creates new form GeneticAlgorithmOptionsPanel
     */
    public GeneticAlgorithmOptionsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectionStrategyButtonGroup = new javax.swing.ButtonGroup();
        geneticAlgorithmOptionsPanel = new javax.swing.JPanel();
        optionsSeparator2 = new javax.swing.JSeparator();
        terminationConditionsLabel = new javax.swing.JLabel();
        generationCountLabel = new javax.swing.JLabel();
        generationCountTextField = new javax.swing.JTextField();
        stagnationActiveLabel = new javax.swing.JLabel();
        selectionStrategyLabel = new javax.swing.JLabel();
        rankSelectionLabel = new javax.swing.JLabel();
        stagnationActiveCheckBox = new javax.swing.JCheckBox();
        rouletteWheelSelectionLabel = new javax.swing.JLabel();
        sigmaScalingSelectionLabel = new javax.swing.JLabel();
        stochasticSelectionLabel = new javax.swing.JLabel();
        tournamentSelectionLabel = new javax.swing.JLabel();
        truncationSelectionLabel = new javax.swing.JLabel();
        optionsSeparator1 = new javax.swing.JSeparator();
        rankSelectionRadioButton = new javax.swing.JRadioButton();
        rouletteWheelSelectionRadioButton = new javax.swing.JRadioButton();
        sigmaScalingSelectionRadioButton = new javax.swing.JRadioButton();
        stochasticSelectionRadioButton = new javax.swing.JRadioButton();
        tournamentSelectionRadioButton = new javax.swing.JRadioButton();
        tournamentSelectionProbabilityLabel = new javax.swing.JLabel();
        randomTournamentSelectionProbabilityCheckBox = new javax.swing.JCheckBox();
        fixedTournamentSelectionProbabilityTextField = new javax.swing.JTextField();
        truncationSelectionRadioButton = new javax.swing.JRadioButton();
        truncationSelectionRatioLabel = new javax.swing.JLabel();
        randomTruncationSelectionRatioCheckBox = new javax.swing.JCheckBox();
        fixedTruncationSelectionRatioTextField = new javax.swing.JTextField();
        maximumNumberOfStagnatedGenerationsLabel = new javax.swing.JLabel();
        maximumNumberOfStagnatedGenerationsTextField = new javax.swing.JTextField();
        fixedMutationProbabilityLabel = new javax.swing.JLabel();
        fixedMutationProbabilityCheckBox = new javax.swing.JCheckBox();
        fixedMutationProbabilityTextField = new javax.swing.JTextField();
        populationNumberLabel = new javax.swing.JLabel();
        populationNumberTextField = new javax.swing.JTextField();
        elitismLabel = new javax.swing.JLabel();
        elitismCheckBox = new javax.swing.JCheckBox();
        elitismTextField = new javax.swing.JTextField();
        initialDataLabel = new javax.swing.JLabel();
        numberOfCrossoverPointsLabel = new javax.swing.JLabel();
        numberOfCrossoverPointsTextField = new javax.swing.JTextField();

        selectionStrategyButtonGroup.add(rankSelectionRadioButton);
        selectionStrategyButtonGroup.add(rouletteWheelSelectionRadioButton);
        selectionStrategyButtonGroup.add(sigmaScalingSelectionRadioButton);
        selectionStrategyButtonGroup.add(stochasticSelectionRadioButton);
        selectionStrategyButtonGroup.add(tournamentSelectionRadioButton);
        selectionStrategyButtonGroup.add(truncationSelectionRadioButton);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        terminationConditionsLabel.setText("Condições de Terminação:");

        generationCountLabel.setText("Número Máximo de Gerações:");

        stagnationActiveLabel.setText("Activar Estagnação?");

        selectionStrategyLabel.setText("Estratégia de Selecção:");

        rankSelectionLabel.setText("Ranking (Fitness Relativo)");

        stagnationActiveCheckBox.setText("Sim");
        if(stagnationActiveCheckBox.isSelected()){
            maximumNumberOfStagnatedGenerationsTextField.setEnabled(true);
        }
        else{
            maximumNumberOfStagnatedGenerationsTextField.setEnabled(false);
        }
        stagnationActiveCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stagnationActiveCheckBoxActionPerformed(evt);
            }
        });

        rouletteWheelSelectionLabel.setText("Roleta Russa");

        sigmaScalingSelectionLabel.setText("Escalabilidade Sigma (desvio padrão)");

        stochasticSelectionLabel.setText("Selecção Estocástica");

        tournamentSelectionLabel.setText("Baseada em Torneio entre pares de soluções");

        truncationSelectionLabel.setText("Truncamento");

        rankSelectionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankSelectionRadioButtonActionPerformed(evt);
            }
        });

        rouletteWheelSelectionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rouletteWheelSelectionRadioButtonActionPerformed(evt);
            }
        });

        sigmaScalingSelectionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigmaScalingSelectionRadioButtonActionPerformed(evt);
            }
        });

        stochasticSelectionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stochasticSelectionRadioButtonActionPerformed(evt);
            }
        });

        tournamentSelectionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectingTournamentSelectionAction(evt);
            }
        });

        tournamentSelectionProbabilityLabel.setText("Valor probabilístico:");

        randomTournamentSelectionProbabilityCheckBox.setText("Aleatório");
        if(tournamentSelectionRadioButton.isSelected()){
            randomTournamentSelectionProbabilityCheckBox.setEnabled(true);
        }
        else{
            randomTournamentSelectionProbabilityCheckBox.setEnabled(false);
        }
        randomTournamentSelectionProbabilityCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomTournamentSelectionProbabilityCheckBoxActionPerformed(evt);
            }
        });

        fixedTournamentSelectionProbabilityTextField.setText("Inserir valor fixo...");
        if (tournamentSelectionRadioButton.isSelected()) {
            fixedTournamentSelectionProbabilityTextField.setEnabled(true);
        } else {
            fixedTournamentSelectionProbabilityTextField.setEnabled(false);
        }

        truncationSelectionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truncationSelectionRadioButtonActionPerformed(evt);
            }
        });

        truncationSelectionRatioLabel.setText("Rácio de candidatos escolhidos:");

        randomTruncationSelectionRatioCheckBox.setText("Aleatório");
        if(tournamentSelectionRadioButton.isSelected()){
            randomTruncationSelectionRatioCheckBox.setEnabled(true);
        }
        else{
            randomTruncationSelectionRatioCheckBox.setEnabled(false);
        }
        randomTruncationSelectionRatioCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomTruncationSelectionRatioCheckBoxActionPerformed(evt);
            }
        });

        fixedTruncationSelectionRatioTextField.setText("Inserir valor fixo...");
        if (tournamentSelectionRadioButton.isSelected()) {
            fixedTruncationSelectionRatioTextField.setEnabled(true);
        } else {
            fixedTruncationSelectionRatioTextField.setEnabled(false);
        }

        maximumNumberOfStagnatedGenerationsLabel.setText("N. Máx. de Gerações Estagnadas:");

        fixedMutationProbabilityLabel.setText("Valor fixo de mutação?");

        fixedMutationProbabilityCheckBox.setText("Sim");
        if (fixedMutationProbabilityCheckBox.isSelected()) {
            fixedMutationProbabilityTextField.setEnabled(true);
        } else {
            fixedMutationProbabilityTextField.setEnabled(false);
        }
        fixedMutationProbabilityCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixedMutationProbabilityCheckBoxActionPerformed(evt);
            }
        });

        populationNumberLabel.setText("Número da população:");

        elitismLabel.setText("Activar Elitistas?");

        elitismCheckBox.setText("Sim");
        if (elitismCheckBox.isSelected()) {
            elitismTextField.setEnabled(true);
        } else {
            elitismTextField.setEnabled(false);
        }
        elitismCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elitismCheckBoxActionPerformed(evt);
            }
        });

        initialDataLabel.setText("Dados iniciais:");

        numberOfCrossoverPointsLabel.setText("Número de pontos de cruzamento:");

        org.jdesktop.layout.GroupLayout geneticAlgorithmOptionsPanelLayout = new org.jdesktop.layout.GroupLayout(geneticAlgorithmOptionsPanel);
        geneticAlgorithmOptionsPanel.setLayout(geneticAlgorithmOptionsPanelLayout);
        geneticAlgorithmOptionsPanelLayout.setHorizontalGroup(
            geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(populationNumberLabel)
                .add(32, 32, 32)
                .add(populationNumberTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(elitismLabel)
                .add(71, 71, 71)
                .add(elitismCheckBox)
                .add(12, 12, 12)
                .add(elitismTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(optionsSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 415, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(selectionStrategyLabel))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(rankSelectionLabel)
                .add(210, 210, 210)
                .add(rankSelectionRadioButton))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(rouletteWheelSelectionLabel)
                .add(292, 292, 292)
                .add(rouletteWheelSelectionRadioButton))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(sigmaScalingSelectionLabel)
                .add(141, 141, 141)
                .add(sigmaScalingSelectionRadioButton))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(stochasticSelectionLabel)
                .add(243, 243, 243)
                .add(stochasticSelectionRadioButton))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(tournamentSelectionLabel)
                .add(94, 94, 94)
                .add(tournamentSelectionRadioButton))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(39, 39, 39)
                .add(tournamentSelectionProbabilityLabel)
                .add(78, 78, 78)
                .add(randomTournamentSelectionProbabilityCheckBox))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(244, 244, 244)
                .add(fixedTournamentSelectionProbabilityTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(truncationSelectionLabel)
                .add(289, 289, 289)
                .add(truncationSelectionRadioButton))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(24, 24, 24)
                .add(truncationSelectionRatioLabel)
                .add(18, 18, 18)
                .add(randomTruncationSelectionRatioCheckBox))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(244, 244, 244)
                .add(fixedTruncationSelectionRatioTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(6, 6, 6)
                .add(optionsSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 423, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(terminationConditionsLabel))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(generationCountLabel)
                .add(6, 6, 6)
                .add(generationCountTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 213, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(stagnationActiveLabel)
                .add(70, 70, 70)
                .add(stagnationActiveCheckBox))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(26, 26, 26)
                .add(maximumNumberOfStagnatedGenerationsLabel)
                .add(12, 12, 12)
                .add(maximumNumberOfStagnatedGenerationsTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 176, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(initialDataLabel)
                    .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                        .add(geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                                .add(fixedMutationProbabilityLabel)
                                .add(31, 31, 31)
                                .add(fixedMutationProbabilityCheckBox))
                            .add(numberOfCrossoverPointsLabel))
                        .add(12, 12, 12)
                        .add(geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(fixedMutationProbabilityTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .add(numberOfCrossoverPointsTextField)))))
        );
        geneticAlgorithmOptionsPanelLayout.setVerticalGroup(
            geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .add(initialDataLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(numberOfCrossoverPointsLabel)
                    .add(numberOfCrossoverPointsTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(fixedMutationProbabilityLabel))
                    .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                        .add(2, 2, 2)
                        .add(fixedMutationProbabilityCheckBox))
                    .add(fixedMutationProbabilityTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(populationNumberLabel))
                    .add(populationNumberTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(elitismLabel))
                    .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                        .add(2, 2, 2)
                        .add(elitismCheckBox))
                    .add(elitismTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(optionsSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12)
                .add(selectionStrategyLabel)
                .add(13, 13, 13)
                .add(geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(rankSelectionLabel))
                    .add(rankSelectionRadioButton))
                .add(6, 6, 6)
                .add(geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(rouletteWheelSelectionLabel))
                    .add(rouletteWheelSelectionRadioButton))
                .add(6, 6, 6)
                .add(geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                        .add(3, 3, 3)
                        .add(sigmaScalingSelectionLabel))
                    .add(sigmaScalingSelectionRadioButton))
                .add(6, 6, 6)
                .add(geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                        .add(2, 2, 2)
                        .add(stochasticSelectionLabel))
                    .add(stochasticSelectionRadioButton))
                .add(6, 6, 6)
                .add(geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                        .add(1, 1, 1)
                        .add(tournamentSelectionLabel))
                    .add(tournamentSelectionRadioButton))
                .add(6, 6, 6)
                .add(geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(tournamentSelectionProbabilityLabel))
                    .add(randomTournamentSelectionProbabilityCheckBox))
                .add(6, 6, 6)
                .add(fixedTournamentSelectionProbabilityTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(6, 6, 6)
                .add(geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                        .add(7, 7, 7)
                        .add(truncationSelectionLabel))
                    .add(truncationSelectionRadioButton))
                .add(12, 12, 12)
                .add(geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(truncationSelectionRatioLabel))
                    .add(randomTruncationSelectionRatioCheckBox))
                .add(6, 6, 6)
                .add(fixedTruncationSelectionRatioTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(6, 6, 6)
                .add(optionsSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12)
                .add(terminationConditionsLabel)
                .add(12, 12, 12)
                .add(geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(generationCountLabel))
                    .add(generationCountTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(stagnationActiveLabel))
                    .add(stagnationActiveCheckBox))
                .add(8, 8, 8)
                .add(geneticAlgorithmOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(geneticAlgorithmOptionsPanelLayout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(maximumNumberOfStagnatedGenerationsLabel))
                    .add(maximumNumberOfStagnatedGenerationsTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30))
        );

        add(geneticAlgorithmOptionsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void enableTournamentSpecificParameters(boolean willEnable) {
        randomTournamentSelectionProbabilityCheckBox.setEnabled(willEnable);
        fixedTournamentSelectionProbabilityTextField.setEnabled(willEnable);
    }

    private void enableTruncationSpecificParameters(boolean willEnable) {
        randomTruncationSelectionRatioCheckBox.setEnabled(willEnable);
        fixedTruncationSelectionRatioTextField.setEnabled(willEnable);
    }

    public HashMap<String, String> extractParameters() {
        HashMap<String, String> parameters = new HashMap<String, String>();

        try {
            initialDataAlgorithmParameters(parameters);
            selectionAlgorithmParameters(parameters);
            terminationConditionParameters(parameters);
        } catch (IllegalArgumentException e) {
            parameters.clear();
            parameters.put("errorMsg", e.getMessage());

            return parameters;
        }

        return parameters;
    }

    private void selectionAlgorithmParameters(HashMap<String, String> parameters) {
        if (tournamentSelectionRadioButton.isSelected()) {
            if (randomTournamentSelectionProbabilityCheckBox.isSelected()) {
                parameters.put("tournamentSelection", "true");
                parameters.put("probabilityValue", "random");
            } else {
                try {
                    parameters.put("tournamentSelection", "true");

                    //This line is important to see if the text corresponds to a number or not.
                    double probability = Double.parseDouble(fixedTournamentSelectionProbabilityTextField.getText());

                    if (probability < 0.0 || probability > 1.0) {
                        throw new IllegalArgumentException("Deverá colocar um número compreendido entre 0 e 1!");
                    }

                    parameters.put("probabilityValue", Double.toString(probability));
                } catch (NumberFormatException e) {
                    throw new IllegalArgumentException("Deverá colocar um número válido!");
                }
            }
        } else if (truncationSelectionRadioButton.isSelected()) {
            if (randomTruncationSelectionRatioCheckBox.isSelected()) {
                parameters.put("truncationSelection", "true");
                parameters.put("ratioValue", "random");
            } else {
                try {
                    parameters.put("truncationSelection", "true");

                    //This line is important to see if the text corresponds to a number or not.
                    double ratio = Double.parseDouble(fixedTruncationSelectionRatioTextField.getText());

                    if (ratio < 0.0 || ratio > 1.0) {
                        throw new IllegalArgumentException("Deverá colocar um número compreendido entre 0 e 1!");
                    }

                    parameters.put("ratioValue", Double.toString(ratio));
                } catch (NumberFormatException e) {
                    throw new IllegalArgumentException("Deverá colocar um número válido!");
                }
            }
        } else if (rankSelectionRadioButton.isSelected()) {
            parameters.put("rankSelection", "true");
        } else if (rouletteWheelSelectionRadioButton.isSelected()) {
            parameters.put("rouletteWheelSelection", "true");
        } else if (sigmaScalingSelectionRadioButton.isSelected()) {
            parameters.put("sigmaScalingSelection", "true");
        } else if (stochasticSelectionRadioButton.isSelected()) {
            parameters.put("stochasticSelection", "true");
        }
    }

    private void terminationConditionParameters(HashMap<String, String> parameters) {
        if (generationCountTextField.getText().equals("")) {
            parameters.put("generationCount", "1");
        } else {
            try {
                //This line is important to see if the text corresponds to a number or not.
                int genCount = Integer.parseInt(generationCountTextField.getText());

                if (genCount < 1) {
                    throw new IllegalArgumentException("Deverá colocar um número válido!");
                } else {
                    parameters.put("generationCount", Integer.toString(genCount));
                }
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException("Deverá colocar um número válido!");
            } catch (IllegalArgumentException e) {
                throw new IllegalArgumentException(e.getMessage());
            }
        }

        if (stagnationActiveCheckBox.isSelected() && !maximumNumberOfStagnatedGenerationsTextField.getText().equals("")) {
            try {
                int maxNumOfStagGen = Integer.parseInt(generationCountTextField.getText());

                if (maxNumOfStagGen < 0) {
                    throw new IllegalArgumentException("Deverá colocar um número válido!");
                } else if (!(maxNumOfStagGen <= 0)) {
                    parameters.put("stagnation", "true");
                    parameters.put("maxNumOfStagGen", Integer.toString(maxNumOfStagGen));
                }
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException("Deverá colocar um número válido!");
            } catch (IllegalArgumentException e) {
                throw new IllegalArgumentException(e.getMessage());
            }
        }
    }

    private void initialDataAlgorithmParameters(HashMap<String, String> parameters) {
        if (numberOfCrossoverPointsTextField.getText().equals("")) {
            parameters.put("numberOfCrossoverPoints", "1");
        } else {
            try {
                int nCrossoverP = Integer.parseInt(numberOfCrossoverPointsTextField.getText());

                if (nCrossoverP < 1) {
                    throw new IllegalArgumentException("Deverá colocar um número válido (mínimo 1 ponto de cruzamento)!");
                } else {
                    parameters.put("numberOfCrossoverPoints", Integer.toString(nCrossoverP));
                }
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException("Deverá colocar um número válido!");
            } catch (IllegalArgumentException e) {
                throw new IllegalArgumentException(e.getMessage());
            }
        }

        if (fixedMutationProbabilityCheckBox.isSelected()) {
            if (fixedMutationProbabilityTextField.getText().equals("")) {
                parameters.put("mutationProbability", "random");
            } else {
                try {
                    double fixedMutation = Double.parseDouble(fixedMutationProbabilityTextField.getText());

                    if (fixedMutation < 0.0 || fixedMutation > 1.0) {
                        throw new IllegalArgumentException("Deverá colocar um número válido (entre 0 e 1)!");
                    } else {
                        parameters.put("mutationProbability", Double.toString(fixedMutation));
                    }
                } catch (NumberFormatException e) {
                    throw new IllegalArgumentException("Deverá colocar um número válido!");
                } catch (IllegalArgumentException e) {
                    throw new IllegalArgumentException(e.getMessage());
                }
            }
        } else if (!fixedMutationProbabilityCheckBox.isSelected()) {
            parameters.put("mutationProbability", "random");
        }

        if (populationNumberTextField.getText().equals("")) {
            parameters.put("initialPopulation", DEFAULT_POPULATION_NUMBER);
        } else {
            try {
                int initialPopulation = Integer.parseInt(populationNumberTextField.getText());

                if (initialPopulation < 2) {
                    throw new IllegalArgumentException("Deverá colocar um número mínimo na população (pelo menos, 2)!");
                } else {
                    parameters.put("initialPopulation", Integer.toString(initialPopulation));
                }
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException("Deverá colocar um número válido!");
            } catch (IllegalArgumentException e) {
                throw new IllegalArgumentException(e.getMessage());
            }
        }

        if (elitismCheckBox.isSelected()) {
            if (elitismTextField.getText().equals("")) {
                parameters.put("elitePopulation", "0");
            } else {
                try {
                    int elitePopulation = Integer.parseInt(elitismTextField.getText());
                    
                    if(elitePopulation < 0){
                        throw new IllegalArgumentException("Deverá colocar um número válido!");
                    }
                    else if(!(elitePopulation < Integer.parseInt(parameters.get("initialPopulation")))){
                        throw new IllegalArgumentException("Deverá colocar um número de elitistas menor que o número total da população!");
                    }
                    else{
                        parameters.put("elitePopulation", Integer.toString(elitePopulation));
                    }
                } catch (NumberFormatException e) {
                    throw new IllegalArgumentException("Deverá colocar um número válido!");
                } catch (IllegalArgumentException e) {
                    throw new IllegalArgumentException(e.getMessage());
                }
            }
        } else if (!elitismCheckBox.isSelected()) {
            parameters.put("elitePopulation", "0");
        }
    }

    private void rankSelectionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankSelectionRadioButtonActionPerformed
        this.enableTournamentSpecificParameters(false);
        this.enableTruncationSpecificParameters(false);
    }//GEN-LAST:event_rankSelectionRadioButtonActionPerformed

    private void randomTruncationSelectionRatioCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomTruncationSelectionRatioCheckBoxActionPerformed
        if (randomTruncationSelectionRatioCheckBox.isSelected()) {
            fixedTruncationSelectionRatioTextField.setEnabled(false);
        } else {
            fixedTruncationSelectionRatioTextField.setEnabled(true);
        }
    }//GEN-LAST:event_randomTruncationSelectionRatioCheckBoxActionPerformed

    private void selectingTournamentSelectionAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectingTournamentSelectionAction
        this.enableTournamentSpecificParameters(true);
        this.enableTruncationSpecificParameters(false);
    }//GEN-LAST:event_selectingTournamentSelectionAction

    private void rouletteWheelSelectionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rouletteWheelSelectionRadioButtonActionPerformed
        this.enableTournamentSpecificParameters(false);
        this.enableTruncationSpecificParameters(false);
    }//GEN-LAST:event_rouletteWheelSelectionRadioButtonActionPerformed

    private void sigmaScalingSelectionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigmaScalingSelectionRadioButtonActionPerformed
        this.enableTournamentSpecificParameters(false);
        this.enableTruncationSpecificParameters(false);
    }//GEN-LAST:event_sigmaScalingSelectionRadioButtonActionPerformed

    private void stochasticSelectionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stochasticSelectionRadioButtonActionPerformed
        this.enableTournamentSpecificParameters(false);
        this.enableTruncationSpecificParameters(false);
    }//GEN-LAST:event_stochasticSelectionRadioButtonActionPerformed

    private void truncationSelectionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truncationSelectionRadioButtonActionPerformed
        this.enableTournamentSpecificParameters(false);
        this.enableTruncationSpecificParameters(true);
    }//GEN-LAST:event_truncationSelectionRadioButtonActionPerformed

    private void randomTournamentSelectionProbabilityCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomTournamentSelectionProbabilityCheckBoxActionPerformed
        if (randomTournamentSelectionProbabilityCheckBox.isSelected()) {
            fixedTournamentSelectionProbabilityTextField.setEnabled(false);
        } else {
            fixedTournamentSelectionProbabilityTextField.setEnabled(true);
        }
    }//GEN-LAST:event_randomTournamentSelectionProbabilityCheckBoxActionPerformed

    private void stagnationActiveCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stagnationActiveCheckBoxActionPerformed
        if (stagnationActiveCheckBox.isSelected()) {
            maximumNumberOfStagnatedGenerationsTextField.setEnabled(true);
        } else {
            maximumNumberOfStagnatedGenerationsTextField.setEnabled(false);
        }
    }//GEN-LAST:event_stagnationActiveCheckBoxActionPerformed

    private void fixedMutationProbabilityCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixedMutationProbabilityCheckBoxActionPerformed
        if (fixedMutationProbabilityCheckBox.isSelected()) {
            fixedMutationProbabilityTextField.setEnabled(true);
        } else {
            fixedMutationProbabilityTextField.setEnabled(false);
        }
    }//GEN-LAST:event_fixedMutationProbabilityCheckBoxActionPerformed

    private void elitismCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elitismCheckBoxActionPerformed
        if (elitismCheckBox.isSelected()) {
            elitismTextField.setEnabled(true);
        } else {
            elitismTextField.setEnabled(false);
        }
    }//GEN-LAST:event_elitismCheckBoxActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox elitismCheckBox;
    private javax.swing.JLabel elitismLabel;
    private javax.swing.JTextField elitismTextField;
    private javax.swing.JCheckBox fixedMutationProbabilityCheckBox;
    private javax.swing.JLabel fixedMutationProbabilityLabel;
    private javax.swing.JTextField fixedMutationProbabilityTextField;
    private javax.swing.JTextField fixedTournamentSelectionProbabilityTextField;
    private javax.swing.JTextField fixedTruncationSelectionRatioTextField;
    private javax.swing.JLabel generationCountLabel;
    private javax.swing.JTextField generationCountTextField;
    private javax.swing.JPanel geneticAlgorithmOptionsPanel;
    private javax.swing.JLabel initialDataLabel;
    private javax.swing.JLabel maximumNumberOfStagnatedGenerationsLabel;
    private javax.swing.JTextField maximumNumberOfStagnatedGenerationsTextField;
    private javax.swing.JLabel numberOfCrossoverPointsLabel;
    private javax.swing.JTextField numberOfCrossoverPointsTextField;
    private javax.swing.JSeparator optionsSeparator1;
    private javax.swing.JSeparator optionsSeparator2;
    private javax.swing.JLabel populationNumberLabel;
    private javax.swing.JTextField populationNumberTextField;
    private javax.swing.JCheckBox randomTournamentSelectionProbabilityCheckBox;
    private javax.swing.JCheckBox randomTruncationSelectionRatioCheckBox;
    private javax.swing.JLabel rankSelectionLabel;
    private javax.swing.JRadioButton rankSelectionRadioButton;
    private javax.swing.JLabel rouletteWheelSelectionLabel;
    private javax.swing.JRadioButton rouletteWheelSelectionRadioButton;
    private javax.swing.ButtonGroup selectionStrategyButtonGroup;
    private javax.swing.JLabel selectionStrategyLabel;
    private javax.swing.JLabel sigmaScalingSelectionLabel;
    private javax.swing.JRadioButton sigmaScalingSelectionRadioButton;
    private javax.swing.JCheckBox stagnationActiveCheckBox;
    private javax.swing.JLabel stagnationActiveLabel;
    private javax.swing.JLabel stochasticSelectionLabel;
    private javax.swing.JRadioButton stochasticSelectionRadioButton;
    private javax.swing.JLabel terminationConditionsLabel;
    private javax.swing.JLabel tournamentSelectionLabel;
    private javax.swing.JLabel tournamentSelectionProbabilityLabel;
    private javax.swing.JRadioButton tournamentSelectionRadioButton;
    private javax.swing.JLabel truncationSelectionLabel;
    private javax.swing.JRadioButton truncationSelectionRadioButton;
    private javax.swing.JLabel truncationSelectionRatioLabel;
    // End of variables declaration//GEN-END:variables
}
